<?php

namespace Luxue\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PressRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PressRepository extends EntityRepository
{
}
