<?php

namespace Luxue\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubwayLineRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SubwayLineRepository extends EntityRepository
{
}
